# Autogenerated wrapper script for Chipmunk_jll for x86_64-apple-darwin
export libchipmunk

JLLWrappers.@generate_wrapper_header("Chipmunk")
JLLWrappers.@declare_library_product(libchipmunk, "@rpath/libchipmunk.7.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libchipmunk,
        "lib/libchipmunk.7.0.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
